name: publish plugin
on:
  branches:
    - main

jobs:
  push:
    name: Publish plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Check code smells
        run: ./gradlew publishPlugins -Pgradle.publish.key=secrets.GRADLE_KEY -Pgradle.publish.secret=secrets.GRADLE_SECRET
  