name: publish plugin
on:
  push:
    branches:
      - main

jobs:
  push:
    name: Publish plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Run unit tests with coverage
        run: ./gradlew clean jacocoTestReport

      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: build/reports/jacoco/test/jacocoTestReport.xml

      - name: send test to codecov
        uses: codecov/codecov-action@v1.3.1

      - name: Make publish executable
        run: chmod +x .github/workflows/publish.sh

      - name: publish gradle plugin
        env:
          GRADLE_KEY: ${{ secrets.GRADLE_KEY }}
          GRADLE_SECRET: ${{ secrets.GRADLE_SECRET }}
        run: |
         .github/workflows/publish.sh `cat VERSION.txt`
  